-- MySQL Script generated by MySQL Workbench
-- Wed Nov 30 14:48:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamento` (
  `CodDpto` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `jefe_dpto` INT NOT NULL,
  PRIMARY KEY (`CodDpto`, `jefe_dpto`),
  INDEX `fk_departamento_profesor1_idx` (`jefe_dpto` ASC) VISIBLE,
  CONSTRAINT `fk_departamento_profesor1`
    FOREIGN KEY (`jefe_dpto`)
    REFERENCES `mydb`.`profesor` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profesor` (
  `DNI` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `Apellido1` VARCHAR(45) NOT NULL,
  `Apellido2` VARCHAR(45) NULL,
  `dpto` INT NOT NULL,
  PRIMARY KEY (`DNI`),
  INDEX `fk_profesor_departamento_idx` (`dpto` ASC) VISIBLE,
  CONSTRAINT `fk_profesor_departamento`
    FOREIGN KEY (`dpto`)
    REFERENCES `mydb`.`departamento` (`CodDpto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alumno` (
  `DNI` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `Apellido1` VARCHAR(45) NOT NULL,
  `Apellido2` VARCHAR(45) NULL,
  `bilingue` ENUM("si", "no") NOT NULL,
  `luger_certificacion` VARCHAR(45) NULL,
  `fecha_certificacion` DATE NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ciclo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ciclo` (
  `CodCiclo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `siglas` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`CodCiclo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`asignatura` (
  `CodAsig` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `NumHoras` INT NOT NULL,
  `ciclo` INT NOT NULL,
  `profesor_DNI` INT NOT NULL,
  `anyo` INT(4) NOT NULL,
  `bilingue` ENUM("si", "no") NOT NULL,
  PRIMARY KEY (`CodAsig`, `anyo`, `profesor_DNI`),
  INDEX `fk_asignatura_ciclo1_idx` (`ciclo` ASC) VISIBLE,
  INDEX `fk_asignatura_profesor1_idx` (`profesor_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_asignatura_ciclo1`
    FOREIGN KEY (`ciclo`)
    REFERENCES `mydb`.`ciclo` (`CodCiclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignatura_profesor1`
    FOREIGN KEY (`profesor_DNI`)
    REFERENCES `mydb`.`profesor` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alumno_has_asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alumno_has_asignatura` (
  `alumno_DNI` INT NOT NULL,
  `asignatura_CodAsig` INT NOT NULL,
  `asignatura_anyo` INT(4) NOT NULL,
  PRIMARY KEY (`alumno_DNI`, `asignatura_CodAsig`, `asignatura_anyo`),
  INDEX `fk_alumno_has_asignatura_asignatura1_idx` (`asignatura_CodAsig` ASC, `asignatura_anyo` ASC) VISIBLE,
  INDEX `fk_alumno_has_asignatura_alumno1_idx` (`alumno_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_alumno_has_asignatura_alumno1`
    FOREIGN KEY (`alumno_DNI`)
    REFERENCES `mydb`.`alumno` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_asignatura_asignatura1`
    FOREIGN KEY (`asignatura_CodAsig` , `asignatura_anyo`)
    REFERENCES `mydb`.`asignatura` (`CodAsig` , `anyo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
