-- MySQL Script generated by MySQL Workbench
-- Mon Dec 12 13:03:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

SET FOREIGN_KEY_CHECKS=0;

-- -----------------------------------------------------
-- Schema integridad2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema integridad2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `integridad2` DEFAULT CHARACTER SET utf8 ;
USE `integridad2` ;

-- -----------------------------------------------------
-- Table `integridad2`.`tblOficio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integridad2`.`tblOficio` (
  `tipo_oficio` INT NOT NULL,
  `bonificacion` INT NOT NULL,
  `horas_semanas` INT(2) NOT NULL,
  PRIMARY KEY (`tipo_oficio`),
  CONSTRAINT CHK_horas_semanas CHECK (horas_semanas>=35 AND horas_semanas<=40))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integridad2`.`tblTrabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integridad2`.`tblTrabajador` (
  `cedula` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `valor_hora` INT(2) NOT NULL,
  `tipo_oficio` INT NOT NULL,
  PRIMARY KEY (`cedula`),
  INDEX `fk_tipo_oficio_idx` (`tipo_oficio` ASC) VISIBLE,
  CONSTRAINT CHK_valor_hora CHECK (valor_hora>=20 AND valor_hora<=35),
  CONSTRAINT `fk_tipo_oficio`
    FOREIGN KEY (`tipo_oficio`)
    REFERENCES `integridad2`.`tblOficio` (`tipo_oficio`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integridad2`.`tblArea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integridad2`.`tblArea` (
  `cod_area` INT NOT NULL,
  `nom_area` VARCHAR(45) NOT NULL,
  `estrato` INT NOT NULL,
  PRIMARY KEY (`cod_area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integridad2`.`tblEdificio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integridad2`.`tblEdificio` (
  `iden_edif` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `tipo` ENUM('oficina', 'comercio', 'almacen', 'residencia') NOT NULL,
  `calidad` ENUM('1', '2', '3', '4', '5') NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `cod_area` INT NOT NULL,
  PRIMARY KEY (`iden_edif`),
  INDEX `fk_cod_area_idx` (`cod_area` ASC) VISIBLE,
  CONSTRAINT `fk_cod_area`
    FOREIGN KEY (`cod_area`)
    REFERENCES `integridad2`.`tblArea` (`cod_area`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integridad2`.`tblAsignar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integridad2`.`tblAsignar` (
  `cedula` INT NOT NULL,
  `iden_edif` INT NOT NULL,
  `fecha_i` DATE NOT NULL,
  `num_dias` INT NOT NULL,
  PRIMARY KEY (`cedula`, `iden_edif`),
  INDEX `fk_iden_edif_idx` (`iden_edif` ASC) VISIBLE,
  CONSTRAINT `fk_cedula`
    FOREIGN KEY (`cedula`)
    REFERENCES `integridad2`.`tblTrabajador` (`cedula`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_iden_edif`
    FOREIGN KEY (`iden_edif`)
    REFERENCES `integridad2`.`tblEdificio` (`iden_edif`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
