-- MySQL Script generated by MySQL Workbench
-- Thu Nov 10 11:49:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`provincia` (
  `provNombre` INT NOT NULL,
  `alicuotaIngresosBrutos` VARCHAR(45) NULL,
  PRIMARY KEY (`provNombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `codCliente` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `provincia_provNombre` INT NOT NULL,
  PRIMARY KEY (`codCliente`),
  INDEX `fk_cliente_provincia1_idx` (`provincia_provNombre` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_provincia1`
    FOREIGN KEY (`provincia_provNombre`)
    REFERENCES `mydb`.`provincia` (`provNombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`factura` (
  `factSucursal` INT NOT NULL,
  `factNumero` INT NOT NULL,
  `facturaFecha` VARCHAR(45) NULL,
  `codCliente` INT NOT NULL,
  PRIMARY KEY (`factSucursal`, `factNumero`),
  INDEX `fk_factura_cliente_idx` (`codCliente` ASC) VISIBLE,
  CONSTRAINT `fk_factura_cliente`
    FOREIGN KEY (`codCliente`)
    REFERENCES `mydb`.`cliente` (`codCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recibo` (
  `recSucursal` INT NOT NULL,
  `recNumero` INT NOT NULL,
  `reciboFecha` VARCHAR(45) NULL,
  `codCliente` INT NOT NULL,
  PRIMARY KEY (`recSucursal`, `recNumero`),
  INDEX `fk_recibo_cliente1_idx` (`codCliente` ASC) VISIBLE,
  CONSTRAINT `fk_recibo_cliente1`
    FOREIGN KEY (`codCliente`)
    REFERENCES `mydb`.`cliente` (`codCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `prodNombre` INT NOT NULL,
  `stkMinimo` VARCHAR(45) NULL,
  PRIMARY KEY (`prodNombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`precioproducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`precioproducto` (
  `fechaDesde` VARCHAR(45) NOT NULL,
  `fechaHasta` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `prodNombre` INT NOT NULL,
  PRIMARY KEY (`fechaDesde`, `prodNombre`),
  INDEX `fk_precioproducto_producto1_idx` (`prodNombre` ASC) VISIBLE,
  CONSTRAINT `fk_precioproducto_producto1`
    FOREIGN KEY (`prodNombre`)
    REFERENCES `mydb`.`producto` (`prodNombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itemfactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`itemfactura` (
  `factSucursal` INT NOT NULL,
  `factNumero` INT NOT NULL,
  `prodNombre` INT NOT NULL,
  `cantidad` VARCHAR(45) NULL,
  INDEX `fk_itemfactura_factura1_idx` (`factSucursal` ASC, `factNumero` ASC) VISIBLE,
  PRIMARY KEY (`factSucursal`, `factNumero`, `prodNombre`),
  INDEX `fk_itemfactura_producto1_idx` (`prodNombre` ASC) VISIBLE,
  CONSTRAINT `fk_itemfactura_factura1`
    FOREIGN KEY (`factSucursal` , `factNumero`)
    REFERENCES `mydb`.`factura` (`factSucursal` , `factNumero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemfactura_producto1`
    FOREIGN KEY (`prodNombre`)
    REFERENCES `mydb`.`producto` (`prodNombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itemrecibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`itemrecibo` (
  `factSucursal` INT NOT NULL,
  `factNumero` INT NOT NULL,
  `recSucursal` INT NOT NULL,
  `recNumero` INT NOT NULL,
  `import` VARCHAR(45) NULL,
  PRIMARY KEY (`factSucursal`, `factNumero`, `recSucursal`, `recNumero`),
  INDEX `fk_itemrecibo_recibo1_idx` (`recSucursal` ASC, `recNumero` ASC) VISIBLE,
  CONSTRAINT `fk_itemrecibo_factura1`
    FOREIGN KEY (`factSucursal` , `factNumero`)
    REFERENCES `mydb`.`factura` (`factSucursal` , `factNumero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemrecibo_recibo1`
    FOREIGN KEY (`recSucursal` , `recNumero`)
    REFERENCES `mydb`.`recibo` (`recSucursal` , `recNumero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
