-- MySQL Script generated by MySQL Workbench
-- Wed Dec 14 13:11:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

SET FOREIGN_KEY_CHECKS=0;

-- -----------------------------------------------------
-- Schema AdrianFH1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AdrianFH1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AdrianFH1` DEFAULT CHARACTER SET utf8 ;
USE `AdrianFH1` ;

-- -----------------------------------------------------
-- Table `AdrianFH1`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdrianFH1`.`Ciudad` (
  `Ciudad` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Ciudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AdrianFH1`.`Farmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdrianFH1`.`Farmacia` (
  `ID_farmacia` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `EstaC` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID_farmacia`, `EstaC`),
  INDEX `fk_ciudad_idx` (`EstaC` ASC) VISIBLE,
  CONSTRAINT CHK_email CHECK (email LIKE '%@%'),
  CONSTRAINT `fk_ciudad`
    FOREIGN KEY (`EstaC`)
    REFERENCES `AdrianFH1`.`Ciudad` (`Ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AdrianFH1`.`Farmaceutico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdrianFH1`.`Farmaceutico` (
  `dni` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `TieneF` INT NOT NULL,
  `estaafectadoC` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`dni`, `TieneF`, `estaafectadoC`),
  INDEX `fk_farmacia_idx` (`TieneF` ASC) VISIBLE,
  INDEX `fk_estaafectado_idx` (`estaafectadoC` ASC) VISIBLE,
  CONSTRAINT `fk_farmacia_farmaceutico`
    FOREIGN KEY (`TieneF`)
    REFERENCES `AdrianFH1`.`Farmacia` (`ID_farmacia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estaafectado`
    FOREIGN KEY (`estaafectadoC`)
    REFERENCES `AdrianFH1`.`Ciudad` (`Ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AdrianFH1`.`Propio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdrianFH1`.`Propio` (
  `dni` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `TieneF` INT NOT NULL,
  PRIMARY KEY (`dni`, `TieneF`),
  INDEX `fk_farmacia_idx` (`TieneF` ASC) VISIBLE,
  CONSTRAINT `fk_farmacia_propio`
    FOREIGN KEY (`TieneF`)
    REFERENCES `AdrianFH1`.`Farmacia` (`ID_farmacia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AdrianFH1`.`Laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdrianFH1`.`Laboratorio` (
  `ID_laboratorio` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_laboratorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AdrianFH1`.`AccionTerapeutica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdrianFH1`.`AccionTerapeutica` (
  `ID_AccionTerapeutica` INT NOT NULL,
  `nombre` ENUM('analgésico', 'antibiótico', 'antipirético', 'antiinflamatorio', 'betabloqueante') NOT NULL,
  PRIMARY KEY (`ID_AccionTerapeutica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AdrianFH1`.`Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdrianFH1`.`Medicamento` (
  `ID_medicamento` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `RealizaL` INT NOT NULL,
  `sirveparaA` INT NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`ID_medicamento`, `RealizaL`, `sirveparaA`),
  INDEX `fk_laboratorio_idx` (`RealizaL` ASC) VISIBLE,
  INDEX `fk_accionterapeutica_idx` (`sirveparaA` ASC) VISIBLE,
  CONSTRAINT `fk_laboratorio`
    FOREIGN KEY (`RealizaL`)
    REFERENCES `AdrianFH1`.`Laboratorio` (`ID_laboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accionterapeutica`
    FOREIGN KEY (`sirveparaA`)
    REFERENCES `AdrianFH1`.`AccionTerapeutica` (`ID_AccionTerapeutica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AdrianFH1`.`FtienestockM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdrianFH1`.`FtienestockM` (
  `Farmacia` INT NOT NULL,
  `Medicamento` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`Farmacia`, `Medicamento`),
  INDEX `fk_medicamento_idx` (`Medicamento` ASC) VISIBLE,
  CONSTRAINT `fk_farmacia`
    FOREIGN KEY (`Farmacia`)
    REFERENCES `AdrianFH1`.`Farmacia` (`ID_farmacia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento`
    FOREIGN KEY (`Medicamento`)
    REFERENCES `AdrianFH1`.`Medicamento` (`ID_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AdrianFH1`.`Monodroga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdrianFH1`.`Monodroga` (
  `ID_monodroga` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_monodroga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AdrianFH1`.`McontieneM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdrianFH1`.`McontieneM` (
  `monodroga` INT NOT NULL,
  `medicamento` INT NOT NULL,
  PRIMARY KEY (`monodroga`, `medicamento`),
  INDEX `fk_medicamento_idx` (`medicamento` ASC) VISIBLE,
  CONSTRAINT `fk_monodroga`
    FOREIGN KEY (`monodroga`)
    REFERENCES `AdrianFH1`.`Monodroga` (`ID_monodroga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_contiene`
    FOREIGN KEY (`medicamento`)
    REFERENCES `AdrianFH1`.`Medicamento` (`ID_medicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
